[build]
  base = "exampleSite"
  publish = "public"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.88.1"
  TZ = "America/Toronto"
  HUGO_MODULE_REPLACEMENTS = "github.com/danielfdickinson/adityatelange-hugo-PaperMod -> ../../../repo"
#  GIT_LFS_ENABLED = "1"
#  GIT_LFS_FETCH_INCLUDE = "*.jpg,*.png,*.jpeg,*.svg,*.gif,*.pdf,*.mp4,*.bmp,*.webp,*.ico"

[context.production]
  command = "hugo --gc ${URL:+-b $URL} --cleanDestinationDir"

[context.deploy-preview]
  command = "hugo --gc ${DEPLOY_PRIME_URL:+-b $DEPLOY_PRIME_URL} --cleanDestinationDir"

[context.branch-deploy]
  command = "hugo --gc ${DEPLOY_PRIME_URL:+-b $DEPLOY_PRIME_URL} --cleanDestinationDir"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"

[[plugins]]
  package = "netlify-plugin-html-validate"

    [plugins.inputs]
      ext = "html"
      config = ".htmlvalidate.json"

[[plugins]]
  package = "netlify-plugin-checklinks"

    [plugins.inputs]
      checkExternal = false
      skipPatterns = [ "<link rel=\"alternate\"", "<meta http-equiv=\"refresh\" content=\"0; url=", "<link rel=\"icon\"", "<link rel=\"apple-touch-icon\"", "<meta property=\"og:url\"" ]

[[plugins]]
  package = "netlify-plugin-minify-html"

    [plugins.inputs.minifierOptions]
    collapseBooleanAttributes = true
    decodeEntities = true
    preserveLineBreaks = true
    removeAttributeQuotes = true
    removeComments = true
    removeEmptyAttributes = true
    removeOptionalTags = true
    removeRedundantAttributes = true
    removeScriptTypeAttributes = true
    removeTypeLinkTypeAttributes = true
    useShortDocType = true

[dev]
  command = "hugo server -s exampleSite --poll 700ms -b http://localhost:8888/ --port 8000"
